#!/bin/sh -e
#
# $Id: autogen,v 1.1.1.1 2007/08/28 15:53:59 psahu Exp $
# 
if [ "x$1" = "xclean" ] ; then 
    # if [ -f Makefile ] ; then 
    # 	make maintainer-clean 
    # fi
    find . -name "*~"            | xargs rm -f 
    find . -name "core"          | xargs rm -f 
    find . -name "Makefile"      | xargs rm -f 
    find . -name "Makefile.in"   | xargs rm -f 
    find . -name "*.o"           | xargs rm -f 
    find . -name "*.lo"          | xargs rm -f 
    find . -name "*.la"          | xargs rm -f 
    find . -name ".libs"         | xargs rm -rf 
    find . -name ".deps"         | xargs rm -rf 
    rm -f build.log build.err configure config.cache config.log \
	config.status libtool aclocal.m4 config.guess config.h \
	config.h.in config.sub install-sh ltconfig ltmain.sh \
	missing mkinstalldirs stamp-h stamp-h.in
    exit 0
fi

libtoolize --automake
touch NEWS README AUTHORS ChangeLog
aclocal
automake -a 
autoconf 
./configure
